extends SceneTree
const Fixtures = preload("res://tests/fixtures.gd")
## 正式教材で判定の状態遷移、重複防止、経過時間を検証する。
func _initialize() -> void:
	var library := Fixtures.library()
	assert(library.load_builtin(), str(library.errors))
	var shift := InspectionShift.new()
	var cases := library.select_cases("", "", "", "initial")
	assert(cases.size() == 2)
	shift.start(cases)
	assert(not shift.decide("unknown"))
	assert(not shift.decide("approve"))
	assert(not shift.decide("ALLOW"))
	var wrong := "block" if shift.current().ground_truth == "allow" else "allow"
	assert(shift.decide(wrong) and shift.score() == 0)
	assert(shift.records.back().ground_truth == cases[0].ground_truth)
	assert(not shift.decide(cases[0].ground_truth))
	assert(shift.advance())
	assert(shift.decide(shift.current().ground_truth) and shift.score() == 1)
	assert(shift.advance() and shift.finished())
	assert(not shift.advance() and not shift.decide("allow"))
	shift.start(cases)
	assert(shift.elapsed_seconds == 0)
	for delta in [-1.0, 0.0, INF, NAN]:
		shift.tick(delta)
	assert(shift.elapsed_seconds == 0)
	shift.tick(4.5)
	shift.tick(10000)
	assert(shift.elapsed_seconds == 10004.5 and not shift.finished())
	assert(shift.records.is_empty())
	assert(shift.decide(shift.current().ground_truth))
	shift.tick(20)
	assert(shift.elapsed_seconds == 10004.5)
	assert(shift.advance())
	shift.tick(2)
	assert(shift.elapsed_seconds == 10006.5)
	assert(shift.decide(shift.current().ground_truth) and shift.advance())
	shift.tick(20)
	assert(shift.finished() and shift.elapsed_seconds == 10006.5)
	shift.start(cases)
	assert(shift.elapsed_seconds == 0)
	assert(shift.score() == 0 and shift.records.is_empty() and shift.observations.is_empty())
	shift.start([])
	shift.tick(20)
	assert(shift.finished() and shift.elapsed_seconds == 0)
	assert(not ProblemLibrary.new().load_builtin("res://data/missing"))
	print("Core state and timer tests passed")
	quit()
