extends SceneTree
## 正式教材で判定の状態遷移、重複防止、制限時間を検証する。
func _initialize() -> void:
	var catalog := ContentCatalog.new()
	assert(catalog.load_pack(), str(catalog.errors))
	var shift := InspectionShift.new()
	var cases := catalog.select_cases("very_beginner")
	assert(cases.size() == 2)
	shift.start(cases, 10)
	assert(not shift.decide("unknown"))
	assert(not shift.decide("approve"))
	assert(not shift.decide("ALLOW"))
	var wrong := "block" if shift.current().ground_truth == "allow" else "allow"
	assert(shift.decide(wrong) and shift.score() == 0)
	assert(shift.records.back().ground_truth == cases[0].ground_truth)
	assert(not shift.decide(cases[0].ground_truth))
	assert(shift.advance())
	assert(shift.decide(shift.current().ground_truth) and shift.score() == 1)
	assert(shift.advance() and shift.finished())
	assert(not shift.advance() and not shift.decide("allow"))
	shift.start(cases, 10)
	shift.tick(4)
	assert(shift.remaining_seconds == 6)
	shift.tick(20)
	assert(shift.remaining_seconds == 0 and shift.timed_out and shift.finished())
	assert(shift.records.is_empty() and not shift.decide("allow") and not shift.advance())
	shift.start(cases, 0)
	shift.tick(10000)
	assert(not shift.finished() and not shift.timed_out)
	assert(shift.decide(shift.current().ground_truth))
	shift.start(cases, 10)
	assert(shift.score() == 0 and shift.records.is_empty() and shift.observations.is_empty())
	assert(not catalog.load_pack("res://data/missing.json") and not catalog.errors.is_empty())
	print("Core state and timer tests passed")
	quit()
